### ISSUE TITLE
Some lines of code don't show on epub version.

### ISSUE THREAD

**Issue by hectorip** [isovector/certainty-by-construction#16]
Hey @isovector! Thank you very much for your great book and work, I'm enjoying it a lot so far. I've noticed some problems with the epub version downloaded from Leanpub. Some text from the code examples is not showing, below are some examples both in Kindle and Apple Books.

![IMG_3588](https://github.com/isovector/certainty-by-construction/assets/1203545/b0a37eb2-58ef-419b-bda5-f084874f85bb)

![IMG_3586](https://github.com/isovector/certainty-by-construction/assets/1203545/8839b10c-3142-4bfa-b623-e32c6905979e)

Thank you very much in advance!

**Comment by isovector** [comment]
Oh my goodness; thanks for the report. I'll look into this!

**Comment by hectorip** [comment]
There you can see another bug, the commands of emacs show in a a strange way.

**Comment by isovector** [comment]
I found the bug; when I was writing some custom agda pipelines, I foolishly hardcoded the fact that I was producing a pdf. These codepaths get completely passed by when building the epub. It shouldn't be too hard to fix.

**Comment by isovector** [comment]
This is harder than I was expecting to fix. But I am indeed working on it!

**Comment by isovector** [comment]
I think I have fixed this problem! Please download a new copy from leanpub and let me know!
