### ISSUE TITLE
Certainty by Construction PDF page 25 MakeCase

### ISSUE THREAD

**Issue by onelinelernen** [isovector/certainty-by-construction#2]
What is "agda:MakeCase" or better "MakeCase" ?

I'm typing along the book in vs code and I'm completely stuck on page 25

Position your cursor on the hole and invoke the agda:MakeCase ,
which will replace our definition with:

Things like "module" and

open Data.Bool
_ : Bool
_ = false

work just fine in agda / vs code on my windows PC with wsl2, but no idea how to use or make sense of the (command ?) "MakeCase"

**Comment by isovector** [comment]
Hi, thanks for reaching out!

`agda:MakeCase` is an annotation in the book I haven't successfully pretty-printed yet. It means to press `Ctrl-C + Ctrl-C`  (to invoke "case split" as [documented here](https://agda.readthedocs.io/en/latest/tools/emacs-mode.html)).  You might need to hit enter again afterwards to make progress.

Sometimes I'll write `MakeCase:x` to suggest that you should press `Ctrl-C + Ctrl-C`, and then type `x` into the pop-up prompt.

**Comment by isovector** [comment]
I've fixed this in the source material, and Friday's update will dramatically clean up the typesetting involved here. Thanks for reporting this!
